### PR TITLE
fix typedefinition

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by popeindustries** [comment]
This doesn’t match the API/signature of the new 6.x version, or am I missing something?

**Comment by taoqf** [comment]
@popeindustries it is nothing to do with node, maybe it's the typescript version is not match. what's the  exact problem?

**Comment by popeindustries** [comment]
On the weekend I published a new version of inline-source (now 6.1.0) and the API has changed: no more `sync` and it returns a promise. I changed the type file to reflect the changes (but it’s possible I didn’t do it correctly). This PR reverts to the now old 5.x inline-source api and signature and won’t work with the new version.

**Comment by taoqf** [comment]
would this do?
```ts
declare namespace inline {
	interface Options {
		attribute: string | boolean;
		compress: boolean;
		fs: any; // like MemoryFileSystem
		handlers: [({ }, { }) => Promise<any>];
		ignore: string[] | { [key: string]: string };
		pretty: boolean;
		rootpath: string;
		saveRemote: boolean;
		svgAsImage: boolean;
		swallowErrors: boolean;
	}
}

declare function inline(htmlpath: string, options?: Partial<inline.Options>): Promise<string>;

export = inline;

```

**Comment by popeindustries** [comment]
that looks better

**Pull request merged**
